language: elixir

sudo: required
dist: trusty

services:
  - docker

elixir:
  - 1.2.3
otp_release:
  - 18.2.1

before_deploy:
  - MIX_ENV=prod mix release
  - cp rel/schnueffelstueck/releases/$(cat version)/schnueffelstueck.tar.gz schnueffelstueck-$(cat version)-linux-x64.tar.gz
  - docker run --rm -v $PWD:$PWD -w $PWD -e "MIX_ENV=prod" msaraiva/elixir-dev sh -c "mix hex.info && mix release"
  - cp rel/schnueffelstueck/releases/$(cat version)/schnueffelstueck.tar.gz schnueffelstueck-$(cat version)-alpine-x64.tar.gz

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Xh/a1UtM1fPFiB6I4SDFURIqYTsi3/96iGki5IKhttLYYT9gaIpLZaKaJIyHYkhoiXF/5mWvLRfWFCBpaI2/Q231sU72YIZ4ZXs2cQW+nDah6W5jgeVy3/apa56FDRnCsfrN3re2TvzSgiD7im7g/gGq1TJqU0uQ2tkEhQiG7OCdKJ33SjMe6oFHoMCCpQgXpQUV9HIArZz03lY4JLQvAeCgRKTWTIZovZbhLeFs2i6qTDvBAmyxjLWSzHtqwMt9XM0FFltq8SIdxaG6+11DtgbtmNcgEn3CabjDxCj34NQBxcxuod0VR5mRZysxYd0nUfeqo6T3etyHZR6TDp7iH7bUc9oDalQ4KxJQ8IuXut7VAEk2OZsdwua2C0b9yI/kiHsVC9Zxy7sqkIKxX9c3+VE7r3KlEsgt5u8KCxm6PWOd3mEOMnsA7QLL1Vut2A6wUfozJJhV3zel3wzt+7sXZLBln6eFLyKjG+NyzujykgTFg2j3tFLfC99L2rVYLtPhPGiCUJLC3+IAl64m6W/7eK1NdvYJ2SDu/ckpITBFHx5gyVUIhbM1dlDzER6z9Mx+csLYQiI1yanAof1BSRoFHEYksZwzc/c79hZZiqNWpMycrnO5HR7w/C0pgPDDaer7VqXzE62JXY8+XnbSBhXPIXvgzCC9XUv/5FX/FkUClL4=
  file:
    - schnueffelstueck-$(cat version)-linux-x64.tar.gz
    - schnueffelstueck-$(cat version)-alpine-x64.tar.gz
  on:
    tags: true
    repo: Jimdo/schnueffelstueck
